export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';

export const LOG_IN_USER_FAILURE = 'LOG_IN_USER_FAILURE';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';

export const LOG_OUT_USER = 'LOG_OUT_USER';
export const FETCH_PARKINGS = 'FETCH_PARKINGS';
export const BOOK_PARKING = 'BOOK_PARKING';
export const RESET_TO_DEFAULT = 'RESET_TO_DEFAULT';
export const SHOW_CURRENT_CAR = 'SHOW_CURRENT_CAR';
export const SHOW_LOADING_BAR = 'SHOW_LOADING_BAR';
export const BACKGROUND_ACTION = 'BACKGROUND_ACTION';
export const STOP_SIMULATION = 'STOP_SIMULATION';
export const START_SIMULATION = 'START_SIMULATION';
export const PARKING_ASSIGNED_MESSAGE = 'PARKING_ASSIGNED_MESSAGE';