export const LOG_IN_USER_SUCCESS = 'LOG_IN_USER_SUCCESS';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const FETCH_PARKINGS_SUCCESS = 'FETCH_PARKINGS_SUCCESS';
export const SHORTEST_DIST_PARKING_SUCCESS = 'SHORTEST_DIST_PARKING_SUCCESS';
export const OUR_ALGO_PARKING_SUCCESS = 'OUR_ALGO_PARKING_SUCCESS';

export const LOG_IN_USER_FAILURE = 'LOG_IN_USER_FAILURE';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';
export const FETCH_PARKINGS_FAILURE = 'FETCH_PARKINGS_FAILURE';
export const SHORTEST_DIST_PARKING_FAILURE = 'SHORTEST_DIST_PARKING_FAILURE';
export const OUR_ALGO_PARKING_FAILURE = 'OUR_ALGO_PARKING_FAILURE';

export const LOG_OUT_USER = 'LOG_OUT_USER'